//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("More.Domain.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aggregate with the identifier &apos;{0}&apos; has been modified and is now greater than or equal to version {1}..
        /// </summary>
        internal static string AggregateVersionOutDated {
            get {
                return ResourceManager.GetString("AggregateVersionOutDated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message type {0} cannot be deserialized. The message must implement {1}..
        /// </summary>
        internal static string CannotDeserializeMessageType {
            get {
                return ResourceManager.GetString("CannotDeserializeMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} cannot be used for the key column..
        /// </summary>
        internal static string InvalidKeyType {
            get {
                return ResourceManager.GetString("InvalidKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISAM persistence must use configurations that all refer to the same database..
        /// </summary>
        internal static string InvalidPersistenceConfiguration {
            get {
                return ResourceManager.GetString("InvalidPersistenceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snapshot type {0} is invalid. The snapshot must be a class, implement IEvent, and implement ISnapshot&lt;TKey&gt;..
        /// </summary>
        internal static string InvalidSnapshotType {
            get {
                return ResourceManager.GetString("InvalidSnapshotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message type {0} is not an event. The type must implement IEvent..
        /// </summary>
        internal static string MessageTypeIsNotAnEvent {
            get {
                return ResourceManager.GetString("MessageTypeIsNotAnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} implementation requires that the {1} snapshot instance also implement IEvent..
        /// </summary>
        internal static string SnapshotMustAlsoBeEvent {
            get {
                return ResourceManager.GetString("SnapshotMustAlsoBeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not supported for correlated properties..
        /// </summary>
        internal static string UnsupportedCorrelationValueType {
            get {
                return ResourceManager.GetString("UnsupportedCorrelationValueType", resourceCulture);
            }
        }
    }
}
