//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Services.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A catalog identifier must be specified to mint tokens..
        /// </summary>
        internal static string InvalidMintItem {
            get {
                return ResourceManager.GetString("InvalidMintItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of ordered tokens must be greater than or equal to 1..
        /// </summary>
        internal static string InvalidMintQuantity {
            get {
                return ResourceManager.GetString("InvalidMintQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A catalog identifier must be specified to order tokens..
        /// </summary>
        internal static string InvalidOrderItem {
            get {
                return ResourceManager.GetString("InvalidOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of ordered tokens must be greater than or equal to 1..
        /// </summary>
        internal static string InvalidOrderQuantity {
            get {
                return ResourceManager.GetString("InvalidOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A catalog identifier must be specified to print tokens..
        /// </summary>
        internal static string InvalidPrintJobItem {
            get {
                return ResourceManager.GetString("InvalidPrintJobItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of printed tokens must be greater than or equal to 1..
        /// </summary>
        internal static string InvalidPrintJobQuantity {
            get {
                return ResourceManager.GetString("InvalidPrintJobQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; HTTP header must be specified..
        /// </summary>
        internal static string MissingHeader {
            get {
                return ResourceManager.GetString("MissingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required service of type {0} is missing..
        /// </summary>
        internal static string MissingRequiredService {
            get {
                return ResourceManager.GetString("MissingRequiredService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested token has already been activated..
        /// </summary>
        internal static string TokenAlreadyActivated {
            get {
                return ResourceManager.GetString("TokenAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested token has already been redeemed..
        /// </summary>
        internal static string TokenAlreadyRedeemed {
            get {
                return ResourceManager.GetString("TokenAlreadyRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A projection request that includes the token code must also include the token hash..
        /// </summary>
        internal static string TokenHashRequired {
            get {
                return ResourceManager.GetString("TokenHashRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified token has been modified by another request..
        /// </summary>
        internal static string TokenModified {
            get {
                return ResourceManager.GetString("TokenModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested token has not been activated..
        /// </summary>
        internal static string TokenNotActivated {
            get {
                return ResourceManager.GetString("TokenNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested token is currently in a reserved state..
        /// </summary>
        internal static string TokenReserved {
            get {
                return ResourceManager.GetString("TokenReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tokens for the requested print job are not yet ready for download, printing has already started, or printing is already complete..
        /// </summary>
        internal static string TokensNotReadyForDownload {
            get {
                return ResourceManager.GetString("TokensNotReadyForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested token has been voided..
        /// </summary>
        internal static string TokenVoided {
            get {
                return ResourceManager.GetString("TokenVoided", resourceCulture);
            }
        }
    }
}
